name: notes_app_hive
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0  # ✅ Ensures proper Hive support
  path_provider: ^2.1.5  # ✅ Required for Hive storage path

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0  # ✅ Ensures latest linting rules
  build_runner: ^2.4.6  # ✅ Required for generating `notes_model.g.dart`
  hive_generator: ^2.0.1  # ✅ Generates Hive type adapters automatically

flutter:
  uses-material-design: true
